/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `IdleSchema`'s JSON-Schema
 * via the `definition` "IdleState".
 */
export type IdleState = "active" | "idle" | "locked";

export interface IdleSchema {
  [k: string]: any;
}
/**
 * This interface was referenced by `IdleSchema`'s JSON-Schema
 * via the `definition` "IdleStateChanged".
 */
export interface IdleStateChanged {
  detectionInterval: number;
  newState: IdleState;
}
