/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WindowSchema {
  [k: string]: any;
}
/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "Window".
 */
export interface Window {
  id: number;
  windowType: string;
  windowState: string;
  incognito: boolean;
  focused: boolean;
}
/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "WindowCreated".
 */
export interface WindowCreated {
  window: Window;
}
/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "WindowFocused".
 */
export interface WindowFocused {
  id: number;
}
/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "WindowRemoved".
 */
export interface WindowRemoved {
  id: number;
}
