/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "WindowType".
 */
export type WindowType = "normal" | "popup" | "panel" | "app" | "devtools";
/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "WindowState".
 */
export type WindowState = "normal" | "minimized" | "maximized" | "fullscreen" | "docked";

export interface WindowSchema {
  [k: string]: any;
}
/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "Window".
 */
export interface Window {
  id?: number;
  windowType?: WindowType;
  windowState?: WindowState;
  incognito: boolean;
  focused: boolean;
  top?: number;
  left?: number;
  width?: number;
  height?: number;
  alwaysOnTop: boolean;
}
/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "WindowCreated".
 */
export interface WindowCreated {
  window: Window;
}
/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "WindowFocused".
 */
export interface WindowFocused {
  id: number;
}
/**
 * This interface was referenced by `WindowSchema`'s JSON-Schema
 * via the `definition` "WindowRemoved".
 */
export interface WindowRemoved {
  id: number;
}
