/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EventSchema {
  [k: string]: any;
}
/**
 * This interface was referenced by `EventSchema`'s JSON-Schema
 * via the `definition` "Event".
 */
export interface Event {
  ts: number;
  tz: number;
  service: string;
  machineID: string;
  eventType: string;
  eventData: null | string;
}
