export enum EventType {
  TAB_ACTIVATED = "TAB_ACTIVATED",
  TAB_UPDATED = "TAB_UPDATED",
  TAB_MOVED = "TAB_MOVED",
  TAB_HIGHLIGHTED = "TAB_HIGHLIGHTED",
  TAB_DETACHED = "TAB_DETACHED",
  TAB_ATTACHED = "TAB_ATACHED",
  TAB_REMOVED = "TAB_REMOVED",

  IDLE = "IDLE",

  WINDOW_FOCUSED = "WINDOW_FOCUSED",
  WINDOW_CREATED = "WINDOW_CREATED",
  WINDOW_REMOVED = "WINDOW_REMOVED"
}
