export enum EventType {
	TAB_ACTIVATED = "TAB_ACTIVATED",
	TAB_UPDATED = "TAB_UPDATED",
	TAB_MOVED = "TYPE_MOVED",
	TAB_HIGHLIGHTED = "TYPE_HIGHLIGHTED",
	TAB_DETACHED = "TYPE_DETACHED",
	TAB_ATTACHED = "TYPE_ATACHED",
	TAB_REMOVED = "TAB_REMOVED",

	IDLE = "IDLE",

	WINDOW_FOCUSED = "WINDOW_FOCUSED",
	WINDOW_CREATED = "WINDOW_CREATED",
	WINDOW_REMOVED = "WINDOW_REMOVED",
};
